### ISSUE TITLE
Wrong link in slides for #1

### ISSUE THREAD

**Issue by toote** [eddelbuettel/t4#1]
In Slide 8 of [the slides for Episode 1](http://dirk.eddelbuettel.com/papers/t4_001_shell_colors.pdf) the link to this same repository has a typo and reads:

https://github.com/eddelbuettel/tf

![Screenshot from 2020-05-11 00-29-04](https://user-images.githubusercontent.com/4922352/81521731-7174bf80-931e-11ea-99cc-fd4095c9c6ff.png)

**Comment by eddelbuettel** [comment]
Thanks for catching that.  Likely from free-form typing.  

Corrected, re-rendered from markdown to latex to pdf and copied.  Should be good now.
