### ISSUE TITLE
Small typo in upgrading to R 4.0.0 slides

### ISSUE THREAD

**Issue by remlapmot** [eddelbuettel/t4#2]
Thanks indeed for this great series.

They weren't part of this series but on slide 10 of your recent "Upgrading to R 4.0.0" talk [here](http://dirk.eddelbuettel.com/papers/r4_upgrade_to_r400.pdf) you have an English grammar typo. The word *lacks* should be *lags*.

**Comment by eddelbuettel** [comment]
Thanks so much for the kind words, and catching that typo.  I just fixed it, re-rendered and copied an updated pdf in place!   Appreciate the hint!
