### ISSUE TITLE
Idea: Custom prompt including git branch

### ISSUE THREAD

**Issue by bryanhanson** [eddelbuettel/t4#3]
Dirk, something I have found really useful is to have a custom prompt that shows the git branch one is working on.

<img width="272" alt="Screen Shot 2020-05-11 at 9 00 50 AM" src="https://user-images.githubusercontent.com/140350/81564733-35654d00-9366-11ea-909e-2f36dd4ac2b7.png">

My skills are no where good enough to create this myself, but I cobbled it together using SO questions.  I'm on OS X so of course adjustments will be needed for other OS's and shells, but I'm sure that's well w/i your skills set.

The code that works for me (`csh`):

```
# The following from https://www.cs.umd.edu/~srhuang/teaching/code_snippets/prompt_color.tcsh.html
# Colors!

set     red="%{\033[1;31m%}"
set   green="%{\033[0;32m%}"
set  yellow="%{\033[1;33m%}"
set    blue="%{\033[1;34m%}"
set magenta="%{\033[1;35m%}"
set    cyan="%{\033[1;36m%}"
set   white="%{\033[0;37m%}"
set     end="%{\033[0m%}" # This is needed at the end... :(

# Setting the actual prompt. Just don't mess with the ${end} guy in either line...
# Also had to Google around & experiment for the exact OS X + csh sed incantation

setenv GIT_BRANCH_CMD "sh -c 'git branch --show-current HEAD 2> /dev/null' | sed -e 's/\(.*\)/\(\1\)/'"

set prompt = "${red}%c2${blue}`$GIT_BRANCH_CMD`${red}>${end} "

# Clean up after ourselves...
unset red green yellow blue magenta cyan yellow white end

```

**Comment by eddelbuettel** [comment]
Yes, great suggestion, that's coming :)   

I once learned that "just standing there / looking over shoulders" in my first Carpentry workshop when co-instructor Karthik had it.  I have one hint on how to do it on [my course site under resources / code snippets](https://stat430.com/resources/snippets/).

**Comment by bryanhanson** [comment]
I shall look forward to it!

**Comment by eddelbuettel** [comment]
Did you get a chance to catch Sunday's episode #002?  Did it fit the bill?

Still wondering if we should have code snippets here too...

**Comment by bryanhanson** [comment]
Hi Dirk... just got caught up (busy start of the week getting GSOC project going).  I'm not generally a big fan of videos, just not my learning style.  But this was excellent.  In terms of delivery, devoting most of the view to the screen is very helpful, and especially your habit of hitting a couple of extra returns between commands makes things easier to see and follow.  Having the slides off to the side also helpful.  Content was very helpful; I had built up a nice prompt by exploring SO, I did not know about these generators and can certainly make use of them in the future.

Additional thoughts for consideration:

* Keep emphasizing building up from simple pieces and focusing on helping folks improve productivity and reduce mistakes.
* Some of us have to use other shells for various reasons, it might be useful to occasionally have cross references to resources in shells other than bash.  I have no idea of the relative popularity of various shells and obviously you don't want to chase down all the options.
* While many or most users might be satisfied with, say, using a generator or just copying a script and using that, some of us also like to know at least a little about the details.   This helps with overall literacy and you never know when you can apply this knowledge.  For example, it would be nice for instance to see a break down of the syntax details of something like `git_parse_branch` -- there's a lot going on there in just a few lines.  But maybe shell scripting is too far from your desired focus.

Keep it up!

**Comment by eddelbuettel** [comment]
Yes, the 'other shells' is a common one.  @KevCaz made the same point via Twitter.  I of course know of `zsh`, `fish`, the new new rust-based thing, ... but somehow I really think there is value in being able to assume a common one _whereever_ one goes, say on ec2 or on the windows wll thing offering (some?) linux or on a random Docker instance or ...   So oddly enough I have resisted this siren song for  my 25+ years with Linux :)

As for discussing 'that syntax': I will need another 25 years to catch. Some things are just hard in bash and best skipped or left to expert: 'calculating' with numbers is one, textual substitution another.  That simply does not into the 'intro' theme.

That said, many many thanks for the encouragement.  I ... also had a healthy scepticism regarding  videos but the combination of recording them for my students (my online course is asynchronous) plus the surprisingly healthy demand out there made me change my mind.

**Comment by KevCaz** [comment]
Did not know about fish :smile: , so once again, thanks! Looking forward watching the next video and learning more!
