### ISSUE TITLE
typo in R and CRAN binaries for Ubuntu

### ISSUE THREAD

**Issue by remlapmot** [eddelbuettel/t4#8]
There is a minor typo in R and CRAN binaries for Ubuntu. On slide 6 in the [slides](https://dirk.eddelbuettel.com/papers/t4_007_ubuntu_binaries.pdf) and on the line [here](https://github.com/eddelbuettel/t4/blob/5bef68664a6cdd1e8f2058ca49a416e8f30db4a4/ubuntuInstalls/fromBasicUbuntuToTidyverse/usingDebBinaries.sh#L7) the *turn of* should be *turn off*.

**Comment by eddelbuettel** [comment]
Thanks!  Fixed in both; updated pdf copied into place.
