### ISSUE TITLE
Intro Byobu slides contents

### ISSUE THREAD

**Issue by famuvie** [eddelbuettel/t4#9]
Dear Dirk,
Just letting you know that the contents of the slides at [https://dirk.eddelbuettel.com/papers/t4_004_byobu_intro.pdf](https://dirk.eddelbuettel.com/papers/t4_004_byobu_intro.pdf) correspond to the contents of the slides at [https://dirk.eddelbuettel.com/papers/t4_007_ubuntu_binaries.pdf](https://dirk.eddelbuettel.com/papers/t4_007_ubuntu_binaries.pdf).

Thanks for all your open work!
ƒacu.-

**Comment by eddelbuettel** [comment]
Thanks for catching that!  I just corrected the file copy error, and [004](https://dirk.eddelbuettel.com/papers/t4_004_byobu_intro.pdf) should provided be the correct and intended file.

Thanks for the heads-up, I hope you are finding these useful.

**Comment by famuvie** [comment]
I certainly do! Thanks again.
